## NumPy Indexing and Selection

In [51]:
import numpy as np

In [52]:
arr = np.arange(0,17)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

#### Bracket Indexing and Selection

In [53]:
arr[5]

5

In [54]:
arr[:3]

array([0, 1, 2])

#### Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [56]:
#Setting a value with index range (Broadcasting)
arr[0:5]=10
arr[7:10]=30
arr

array([10, 10, 10, 10, 10,  5,  6, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16])

In [57]:
# Reset array
arr = np.arange(0,17)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [58]:
slice_of_arr = arr[0:8]
slice_of_arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [59]:
#Change Slice
slice_of_arr[:]=56
slice_of_arr

array([56, 56, 56, 56, 56, 56, 56, 56])

Now note the changes also occur in our original array!

In [60]:
arr

array([56, 56, 56, 56, 56, 56, 56, 56,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [61]:
#To get a copy, need to be explicit
arr_copy = arr.copy()
arr_copy[:]=80
arr_copy

array([80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80])

In [62]:
arr

array([56, 56, 56, 56, 56, 56, 56, 56,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### Indexing a 2D array (matrices)

  Using two subscripts approach i.e. **arr_2d[row][col]** or using one subscript comma approach i.e. **arr_2d[row,col]**. 

In [63]:
arr_2d = np.array(([3,6,9],[10,15,20],[20,25,30],[90,67,56]))
arr_2d

array([[ 3,  6,  9],
       [10, 15, 20],
       [20, 25, 30],
       [90, 67, 56]])

In [64]:
arr_2d[2]

array([20, 25, 30])

In [65]:
#Indexing multiple rows
arr_2d[[2,3]]

array([[20, 25, 30],
       [90, 67, 56]])

In [66]:
# Format is arr_2d[row][col] or arr_2d[row,col]
# Getting individual element value
arr_2d[2,0]

20

In [67]:
# Getting individual element value
arr_2d[2,0]

20

In [71]:
# 2D array slicing
#Shape (2,2) from top right corner ######Doubt
arr_2d[0:3,1:]

array([[ 6,  9],
       [15, 20],
       [25, 30]])

In [69]:
#Shape bottom row
arr_2d[2:5,4:7]

array([], shape=(2, 0), dtype=int32)

### Selection

Selecting/Filtering data based on some conditions.

In [17]:
arr1 = np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
arr1 > 7

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [52]:
bool1 = arr>7

In [53]:
bool1

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [18]:
arr1[arr1>7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
arr1[arr1==12]

array([12])