# NumPy 

NumPy --> Numeric Python, it is a Linear Algebra Library for Python.
            It is the basic building block for almost all python compatible data science libraries.

Numpy is also incredibly fast. Here, Numpy arrays are used instead of normal python lists.

#### Importing NumPy

In [5]:
import numpy as np

## Why Numpy?

#### case 1

In [6]:
list1 = list(range(1,100,5))
print(list1)
for i in range(len(list1)):
    list1[i]=list1[i]+5
print(list1)

[1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96]
[6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96, 101]


In [7]:
arr1 = np.arange(1,100,5)
print(arr1)
arr1 = arr1+5
print(arr1)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
[  6  11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86  91
  96 101]


#### case 2

In [8]:
import random

In [9]:
%%time
for j in range(1000):
    list1 = list(range(1,1000,3))
    #print(list1)
    list2 = list(range(2,1001,3))
    #print(list2)
    #list1 + list2
    list3 = []
    for i in range(len(list1)):
        list3.append(list1[i]+list2[i])
#print(list3)

Wall time: 225 ms


In [10]:
%%time
for x in range(1000):
    a = np.arange(1,1000,3)
    b = np.arange(2,1001,3)
    c = a+b

Wall time: 11 ms


Numpy has many built-in functions and capabilities. Let's see the most important and commonly used aspects of Numpy: vectors,arrays,matrices, and number generation.
## Numpy Arrays

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d.

### Various ways to create NumPy Arrays

#### 1. From a normal Python List

We can create a Numpy array by directly converting a list or list of lists:

In [11]:
list1 = [10,20,30]
list1

[10, 20, 30]

#### np.array(list1)

In [45]:
matrix1 = [[10,20,30],[40,50,600],[70,80,90]]
matrix2=matrix1[1:3]
matrix2

[[40, 50, 600], [70, 80, 90]]

In [46]:
np.array(matrix2)

array([[ 40,  50, 600],
       [ 70,  80,  90]])

#### 2. Using Built-in Methods

There are many built-in methods to generate Numpy Arrays.

### a. arange

Returns a range of values for the specified interval.

In [14]:
np.arange(0,18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [15]:
np.arange(10,99,5)  #1st argument- start value, 2nd argument - end value(exclusive), 3rd argument - step size                                                                                                       

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [12]:
np.arange(19,1,-2)

array([19, 17, 15, 13, 11,  9,  7,  5,  3])

In [16]:
np.arange(1,18,-2)

array([], dtype=int32)

In [17]:
np.arange(-18,1, -1)

array([], dtype=int32)

### b. zeros and ones

Generate arrays of zeros or ones.

In [18]:
np.zeros(4)

array([0., 0., 0., 0.])

In [51]:
np.zeros((4,3)) #argument is a tuple, in tuple we need to specify number of rows and columns 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### c. linspace
Returns evenly spaced numbers over a specified interval.

In [22]:
np.linspace(0,10,3) #3rd argument for total numbers to be generated.

array([ 0.,  5., 10.])

In [23]:
np.linspace(10,100,5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [24]:
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

### d. eye

Creates an identity matrix

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 3. Generating Random number arrays

Numpy also has many inbuilt functions to generate random number arrays:

#### a. rand
Generates uniformly distributed random numbers over ``[0, 1)``.

In [52]:
np.random.rand(5)

array([0.71189156, 0.23843835, 0.58814347, 0.36671969, 0.93738682])

In [29]:
np.random.rand(4,4)

array([[0.59979273, 0.62183841, 0.26159981, 0.7991701 ],
       [0.17341575, 0.25528026, 0.5025913 , 0.33704497],
       [0.08584838, 0.74518403, 0.88994183, 0.77780027],
       [0.35659552, 0.42352221, 0.94660821, 0.55251356]])

### randn

Generates normally distributed(standard normal distribution) random numbers.

In [53]:
np.random.randn(4)

array([ 0.55574193, -0.14209042,  0.02621211,  0.54166878])

In [63]:
np.random.randn(4,4)

array([[ 1.0697737 ,  0.502517  ,  0.93056072,  1.84967456],
       [ 2.48588249,  0.20786339,  0.63173231,  0.96374407],
       [-1.16602456,  1.09423513, -0.09655209,  0.01821752],
       [-0.94320119,  0.99066488,  0.88519995,  0.12503768]])

### randint
Generates random integers over given range.

In [65]:
np.random.randint(12,100)

46

In [67]:
np.random.randint(12,100,9) #3rd argument for total numbers to be generated.

array([56, 99, 91, 22, 40, 55, 18, 83, 73])

### Array Attributes and Methods

In [69]:
array1 = np.arange(20)
randomarray1 = np.random.randint(0,50,10)

In [70]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
array1.shape

(20,)

In [76]:
randomarray1

array([36, 42,  0,  6, 19, 43,  8,  1, 14, 22])

## Reshape
change the original shape(dimension) of the array.

In [10]:
arr1 =array1.reshape(4,5)

In [13]:
arr1.shape[1]

5

### max,min,argmax,argmin

max(), min() for finding minimum and maximum value.
argmax(),argmin() for index of min and max elements.

In [78]:
randomarray1

array([36, 42,  0,  6, 19, 43,  8,  1, 14, 22])

In [79]:
randomarray1.max()

43

In [80]:
randomarray1.argmax()

5

In [81]:
randomarray1.min()

0

In [82]:
randomarray1.argmin()

2

## Shape

Shape is an attribute that denotes dimension(shape) of array.

In [19]:
# Vector
array1.shape

(20,)

In [20]:
# Notice the two sets of brackets
array1.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [20]:
array1.reshape(1,20).shape

(1, 20)

In [21]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
array1.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [24]:
array1.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

### dtype

To get the data type of the object in the array:
* similar method : np.result_type()

In [85]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [86]:
array1.dtype

dtype('int32')

In [87]:
np.result_type(array1)

dtype('int32')

In [53]:
array2 = np.arange(0, 10, 1.33,dtype=np.int32)
array2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [56]:
array3 = np.arange(0, 10, 2,dtype=np.float64)
array3

array([0., 2., 4., 6., 8.])

#### type 
type() returns class type of an object.

In [57]:
type(array1)

numpy.ndarray

In [1]:
type(array2)

NameError: name 'array2' is not defined

In [ ]:
np.