## NumPy Operations

### Arithmetic
Basic arithmetic operations: +,-,*,/,%.
Can be performed like array with array arithmetic, or scalar with array arithmetic.

In [15]:
import numpy as np
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [2]:
arr + arr

array([0, 2, 4, 6, 8])

In [3]:
arr * arr

array([ 0,  1,  4,  9, 16])

In [4]:
arr

array([0, 1, 2, 3, 4])

In [5]:
# Warning on division by zero
# divison by zero replaced with nan
arr/arr

C:\Users\d943770\OneDrive - Telstra\Desktop\LAAN IMP Folder\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.])

In [6]:
# Also warning,instead of nan here inf(infinity)
1/arr

C:\Users\d943770\OneDrive - Telstra\Desktop\LAAN IMP Folder\Anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [7]:
arr**3

array([ 0,  1,  8, 27, 64], dtype=int32)

### Some universal Array Functions

In [8]:
#for Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [9]:
#for exponential (e^)
np.exp(arr)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [10]:
arr

array([0, 1, 2, 3, 4])

In [11]:
np.max(arr) #same as arr.max()

4

In [12]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [13]:
np.log(arr)

C:\Users\d943770\OneDrive - Telstra\Desktop\LAAN IMP Folder\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [52]:
a=[2,4,5]
a1=np.array(a)

In [53]:
b=[[3,2,4],[6,7,8],[9,10,12]]
b1=np.array(b)

In [54]:
b1

array([[ 3,  2,  4],
       [ 6,  7,  8],
       [ 9, 10, 12]])

In [55]:
a1*b1 ##Multipication

array([[ 6,  8, 20],
       [12, 28, 40],
       [18, 40, 60]])

In [56]:
np.multiply(a1,b1)

array([[ 6,  8, 20],
       [12, 28, 40],
       [18, 40, 60]])

In [59]:
a1.dot(b1) ##Matrix multiplication

array([ 75,  82, 100])